Portfolio: application deploy
mahdimahdawi/mahdimahdawi.github.io pull request #1
Opened 2022-07-11 14:22 UTC by mahdimahdawi

- Modified README.md file
- Added project to github pages

2022-07-11 14:37 UTC, DammyShittu requested changes
Hi @mahdimahdawi,

✔️ Portfolio is properly deployed

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-11 14:37 UTC, DammyShittu commented on README.md
> +- Github pages: [Mahdi-portfolio] https://mahdimahdawi.github.io
- [ ] From the [readme template from Microverse](https://github.com/microverseinc/readme-template) we can see that the live link has its own section. Kindly move this link to its own section as well for better visibility and organization.

2022-07-12 03:22 UTC, mahdimahdawi commented
- Online link now available in Live section of README.md file.

2022-07-12 03:39 UTC, mahdimahdawi commented
- Online link of portfolio project now available on live section of README.md file.

2022-07-12 03:44 UTC, Reem-lab approved these changes
# Hi @mahdimahdawi, 👋🏻👋🏻 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🔥🔥🔥💯💯

## Highlights
 - Good Commits messages ✅✅
 - Descriptive pull request and branch name ✅✅
 - No Linters error✅✅

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-12 06:47 UTC, merged